import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

// Navbar 컴포넌트
import Link from "next/link";

function Navbar() {
  return (
    <nav className="shadow-md">
      <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
        <h1 className="text-xl font-bold">Our Wedding</h1>
        <div>
          <Link href="/" className="px-4 py-2 text-gray-600">Home</Link>
          <Link href="/gallery" className="px-4 py-2 text-gray-600">Gallery</Link>
        </div>
      </div>
    </nav>
  );
}

// Footer 컴포넌트
function Footer() {
  return (
    <footer className="text-center py-4 text-gray-600">
      <p>© 2024 Wedding Invitation. All rights reserved.</p>
    </footer>
  );
}