# 다른 이미지 경로들을 필요에 따라 추가하세요.
# 예를 들어:
# eventImages:
#   birthday: "/images/events/birthday_banner.png"
heroImage: "/images/DSC07684.jpg"
profileImages:
  bride: "/images/DSC07705.jpg"
  groom: "/images/DSC08024.jpg"
carouselImages: "/images/carousel"
hyImages: "/images/hyfilm"
video: "/videos/beauty_n_beast.mp4"
