name: Claude with Custom App
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prompt:
        description: "The prompt to send to Claude"
        required: true
        default: "Update the API documentation in README.md to reflect the changes made to the API endpoints in this PR."


jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      # Generate a token from your custom app
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Use Claude with your custom app's token
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # ... other configuration
          direct_prompt: |
            Update the API documentation in README.md to reflect
            the changes made to the API endpoints in this PR.